### ISSUE TITLE
shaibos-taxfiling sąskaitos nr.

### ISSUE THREAD

**Issue by vitalikaz** [pypt/shaibos#2]
Sąskaitos numerius galėtu scrapint'i iš URL'ų, o ne pateikti pačius URL. Jeigu yra daug sąskaitų skirtingiems bankams, tai arba rodyti visus, arba per argumentą galima būtų nurodyti kuris bankas domina.

![Shaibos goes smarter](http://i.imgur.com/avlx3yo.png)

Artimiausiomis dienomis galbūt padarysiu ir PR :)

**Comment by pypt** [comment]
Nežinau nežinau, įmokos kodai irgi hardcodinti, be to tos sąskaitos nesikeičia metų metus, tai nežinau ar beverta čia kažką scrapinti.

Bent jau Swedbankas savo el. bankininkystėj viršuj išmeta notificationą, jeigu koks nors populiarus įmokos kodas / sąskaita pasikeitė.

Jaučiu, kad paprasčiau doublecheckint tuos kodus prieš pervedant pinigus.
